[versions]
agp = "8.11.0"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.14.0-alpha02"
constraintlayout       = "2.2.1"
coil                   = "2.7.0"
recyclerView           = "1.4.0"
coroutines             = "1.10.2"
koin                   = "4.1.0"
room                   = "2.7.2"
multidex               = "2.0.1"
preference             = "1.2.1"
viewpager              = "1.1.0"
datastorePreferences   = "1.1.7"
datastoreCore          = "1.1.7"
#       googleAds              = "20.6.0"
dexter                 = "6.2.3"
annotation             = "1.9.1"
coreSplashscreen = "1.0.1"
navigation             = "2.9.0"
compose               = "2025.06.01"
googleServicesPlugin = "4.4.3"
ksp = "2.2.0-2.0.2"
playServicesLocation = "21.3.0"
charty = "2.1.0-beta03.4"
ktorVersion = "3.1.3"
uiToolingPreviewAndroid = "1.8.3"
uiTooling = "1.8.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
dexter = { group = "com.karumi", name = "dexter", version.ref = "dexter" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
#ads = { module = "com.google.android.gms:play-services-ads", version.ref = "googleAds" }
navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
compose-bom ={ group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCore" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
charts = { module = "com.himanshoe:charty", version.ref = "charty" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client = { module = "io.ktor:ktor-client-android", version.ref = "ktorVersion" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktorVersion" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorVersion" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services-plugin = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
navigation-safeargs-plugin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

